name: GitHub Actions Demo
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Set Node.js 18.x
        with:
          node-version: 18.x
      - name: install modules
        run: npm install
      - name: unit test
        run: npm run test
