name: GitHub Actions Demo
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build
      - name: unit test
        run: npm run test
